[CSB]
DataPath=./modules/texts/rawtext/csb/
ModDrv=RawText
Version=1.1
Lang=en
Encoding=UTF-8
Description=Christian Standard Bible
About=The Christian Standard Bible presents the truth of God’s Word with accuracy and clarity for today’s readers, equipping them for lifelong discipleship. It’s a Bible you can teach from with confidence and a Bible you can share with your neighbor hearing God’s Word for the very first time.
LCSH=Bible. English.
DistributionLicense=Public Domain
TextSource=CCEL
