[ESV]
DataPath=./modules/texts/rawtext/esv/
ModDrv=RawText
Version=1.1
Lang=en
Encoding=UTF-8
Description=English Standard Bible
About=The English Standard Version (ESV) is an "essentially literal" translation of the Bible in contemporary English. Created by a team of more than 100 leading evangelical scholars and pastors, the ESV Bible emphasizes "word-for-word" accuracy, literary excellence, and depth of meaning.
LCSH=Bible. English.
DistributionLicense=Public Domain
TextSource=CCEL
