[LSB]
DataPath=./modules/texts/rawtext/lsb/
ModDrv=RawText
Version=1.1
Lang=en
Encoding=UTF-8
Description=Legacy Standard Bible
About=The LSB advances the aim of the NASB. It brings out textual connections through consistent translation of words, highlights literary artistry like alliteration, and tightens grammatical structure. With this new level of precision, the Bible reader is able to see more of what is happening in the original text than ever before.
LCSH=Bible. English.
DistributionLicense=Public Domain
TextSource=CCEL
