[NIV]
DataPath=./modules/texts/rawtext/niv/
ModDrv=RawText
Version=1.1
Lang=en
Encoding=UTF-8
Description=New International Version
About=With more than 650 million copies distributed worldwide, the New International Version (NIV) is the most widely read Bible translation in contemporary English. The NIV Bible delivers the very best combination of accuracy, readability, and clarity, making it easy to read and easy to understand. It is true to God’s Word and true to the reader.
LCSH=Bible. English.
DistributionLicense=Public Domain
TextSource=CCEL
