[NKJV]
DataPath=./modules/texts/rawtext/nkjv/
ModDrv=RawText
Version=1.1
Lang=en
Encoding=UTF-8
Description=New King James Version
About=In 1975, more than two-hundred years since the King James Version’s last update, the boldest and most extensive revision in the history of modern Bible publishing began. With a 130-person team of Greek, Hebrew, and English scholars, editors, church leaders, and Christian laity Thomas Nelson Publishers sought to preserve the accuracy and poetry of the King James Version, but in a language that the everyday person could understand. In 1979 the NKJV New Testament was finished, releasing only the Book of Psalms in 1980. In 1982, the New King James Version was released in its entirety, seven years after its commission, making it the fifth major revision to the beloved King James Version.
LCSH=Bible. English.
DistributionLicense=Public Domain
TextSource=CCEL
