[NRSVUE]
DataPath=./modules/texts/rawtext/nrsvue/
ModDrv=RawText
Version=1.1
Lang=en
Encoding=UTF-8
Description=New Revised Standard Version Updated Edition
About=The New Revised Standard Version, Update Edition (NRSVue) is the foremost Bible translation vetted by Protestant, Catholic, Orthodox, Evangelical, and Jewish scholars. Renowned for its beautiful balance of scholarship and readability, the NRSVue aims to faithfully serve the church in personal spiritual formation, in the liturgy, and in the academy. With revisions based on new textual evidence, historical insights, and linguistic precision, the NRSVue delivers a translation of Scripture based on meticulous care for accuracy and readability.
LCSH=Bible. English.
DistributionLicense=Public Domain
TextSource=CCEL
