[NRSV]
DataPath=./modules/texts/rawtext/nrsv/
ModDrv=RawText
Version=1.1
Lang=en
Encoding=UTF-8
Description=New Revised Standard Version
About=The 1989 New Revised Standard is a popular translation that follows in the traditions of the King James and Revised Standard Versions. It was written with the goal of preserving the best of the older versions while incorporating modern English. The New Revised Standard Version (NRSV) first appeared in 1989, and has received wide acclaim and broad support from academics and church leaders as a Bible for all Christians.
LCSH=Bible. English.
DistributionLicense=Public Domain
TextSource=CCEL
