[OpenGNT]
DataPath=./modules/texts/rawtext/opengnt/
ModDrv=RawText
Version=1.1
Lang=grc
Encoding=UTF-8
Description=Open Greek New Testament
About=Open Greek New Testament Project aims to:

    offer a FREE NA-equivalent text of Greek New Testament, compiled from open-resources;
    align a FREE NA-equivalent Greek New Testament with a group of high-quality and open-source materials;
    develop an online reader for FREE ACCESS of major resources integrated in this project. [OpenGNT.com]

The FREE NA-equivalent text is named as "Open Greek New Testament [OGNT]". The text of OGNT was built upon and compiled from a group of high-quality scholarly materials. It serves as the base text for the rest of the project. This provides all bible readers, students or scholars a FREE text of Greek New Testament, which is the closest equivalent to the text of NA28 / NA27, for studies or research purposes. 
LCSH=Bible. Greek.
DistributionLicense=CC BY-SA 4.0
TextSource=CCEL
